name: Deploy Prod
concurrency:
  group: prod
  cancel-in-progress: false

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AZURE_FUNCTIONAPP_PACKAGE_PATH: 'src'
      PYTHON_VERSION: '3.9'                           
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      TF_VAR_hospitable_email: ${{ secrets.HOSPITABLE_EMAIL }}
      TF_VAR_hospitable_password: ${{ secrets.HOSPITABLE_PASSWORD }}
      TF_VAR_wyze_email: ${{ secrets.WYZE_EMAIL }}
      TF_VAR_wyze_password: ${{ secrets.WYZE_PASSWORD }}
      TF_VAR_wyze_key_id: ${{ secrets.WYZE_KEY_ID }}
      TF_VAR_wyze_api_key: ${{ secrets.WYZE_API_KEY }}
      TF_VAR_slack_token: ${{ secrets.SLACK_TOKEN }}
      TF_VAR_aad_objectId_admin: ${{ secrets.AAD_OBJECTID_ADMIN }}
      TF_VAR_app_name: 'sync-locks'
      TF_VAR_app_name_no_spaces: 'synclocks'
      TF_VAR_non_prod: 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Zip Functions Src code
        run: |
          rm -rf temp src.zip && mkdir temp && cp -r ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/* temp

      - name: Package Functions
        run: |
          docker run --rm --mount type=bind,src=$(pwd)/temp,target=/app python:${{ env.PYTHON_VERSION }} /bin/sh -c 'apt update && apt install git -y && pip3 install -r /app/requirements.txt -t /app'
          cd temp
          rm requirements.txt
          zip -rq ../src.zip ./*
          cd ..

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: ./terraform

     