name: Azure Function CI/CD
concurrency:
  group: deploy
  cancel-in-progress: false

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      TF_VAR_hospitable_email: ${{ secrets.HOSPITABLE_EMAIL }}
      TF_VAR_hospitable_password: ${{ secrets.HOSPITABLE_PASSWORD }}
      TF_VAR_wyze_email: ${{ secrets.WYZE_EMAIL }}
      TF_VAR_wyze_password: ${{ secrets.WYZE_PASSWORD }}
      TF_VAR_wyze_key_id: ${{ secrets.WYZE_KEY_ID }}
      TF_VAR_wyze_api_key: ${{ secrets.WYZE_API_KEY }}
      TF_VAR_slack_token: ${{ secrets.SLACK_TOKEN }}
      TF_VAR_aad_objectId_admin: ${{ secrets.AAD_OBJECTID_ADMIN }}


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
            client-id: ${{ secrets.AZURE_AD_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_AD_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 

      - name: Get Publish Profile Timmer
        id: getPublishProfileTimmer
        uses: Azure/cli@v1.0.0
        with:
          inlineScript: |
            az functionapp deployment list-publishing-profiles --name sync-locks-job --resource-group sync-locks --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} --output tsv > sync_locks_job.publishsettings
            cat sync_locks_job.publishsettings
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}

      - name: Get Publish Profile HTTP
        id: getPublishProfileHTTP
        uses: Azure/cli@v1.0.0
        with:
          inlineScript: |
            az functionapp deployment list-publishing-profiles --name sync-locks-trigger --resource-group sync-locks --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} --output tsv > sync_locks_trigger.publishsettings
            cat sync_locks_trigger.publishsettings
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}

      - name: Deploy Timed Trigger Function
        uses: Azure/functions-action@v1
        with:
          app-name: sync-locks-job
          package: src/timed_trigger
          publish-profile: ${{ steps.getPublishProfileTimmer.outputs.sync_locks_job }}

      - name: Deploy HTTP Trigger Function
        uses: Azure/functions-action@v1
        with:
          app-name: sync-locks-trigger
          package: src/http_trigger
          publish-profile: ${{ steps.getPublishProfileHTTP.outputs.sync_locks_trigger }}
